
Debian Security Advisory
========================


DSA-3151-1 python-django -- security update
-------------------------------------------



Date Reported:
03 Feb 2015
Affected Packages:

[python-django](https://packages.debian.org/src:python-django)

Vulnerable:
Yes
Security database references:
In the Debian bugtracking system: [Bug 775375](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775375).  
In Mitre's CVE dictionary: [CVE-2015-0219](https://security-tracker.debian.org/tracker/CVE-2015-0219), [CVE-2015-0220](https://security-tracker.debian.org/tracker/CVE-2015-0220), [CVE-2015-0221](https://security-tracker.debian.org/tracker/CVE-2015-0221).  

More information:

Several vulnerabilities were discovered in Django, a high-level Python
web development framework. The Common Vulnerabilities and Exposures
project identifies the following problems:


* [CVE-2015-0219](https://security-tracker.debian.org/tracker/CVE-2015-0219)
Jedediah Smith reported that the WSGI environ in Django does not
 distinguish between headers containing dashes and headers containing
 underscores. A remote attacker could use this flaw to spoof WSGI
 headers.
* [CVE-2015-0220](https://security-tracker.debian.org/tracker/CVE-2015-0220)
Mikko Ohtamaa discovered that the django.util.http.is\_safe\_url()
 function in Django does not properly handle leading whitespaces in
 user-supplied redirect URLs. A remote attacker could potentially use
 this flaw to perform a cross-site scripting attack.
* [CVE-2015-0221](https://security-tracker.debian.org/tracker/CVE-2015-0221)
Alex Gaynor reported a flaw in the way Django handles reading files
 in the django.views.static.serve() view. A remote attacker could
 possibly use this flaw to mount a denial of service via resource
 consumption.


For the stable distribution (wheezy), these problems have been fixed in
version 1.4.5-1+deb7u9.


For the upcoming stable distribution (jessie), these problems have been
fixed in version 1.7.1-1.1.


For the unstable distribution (sid), these problems have been fixed in
version 1.7.1-1.1.


We recommend that you upgrade your python-django packages.





