
Debian Security Advisory
========================


DSA-4609-1 python-apt -- security update
----------------------------------------



Date Reported:
23 Jan 2020
Affected Packages:

[python-apt](https://packages.debian.org/src:python-apt)

Vulnerable:
Yes
Security database references:
In the Debian bugtracking system: [Bug 944696](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944696).  
In Mitre's CVE dictionary: [CVE-2019-15795](https://security-tracker.debian.org/tracker/CVE-2019-15795), [CVE-2019-15796](https://security-tracker.debian.org/tracker/CVE-2019-15796).  

More information:

Two security issues were found in the Python interface to the apt
package manager; package downloads from unsigned repositories were
incorrectly rejected and the hash validation relied on MD5.


For the oldstable distribution (stretch), these problems have been fixed
in version 1.4.1.


For the stable distribution (buster), these problems have been fixed in
version 1.8.4.1.


We recommend that you upgrade your python-apt packages.


For the detailed security status of python-apt please refer to
its security tracker page at:
<https://security-tracker.debian.org/tracker/python-apt>





