
Debian Security Advisory
========================


DSA-2758-1 python-django -- denial of service
---------------------------------------------



Date Reported:
17 Sep 2013
Affected Packages:

[python-django](https://packages.debian.org/src:python-django)

Vulnerable:
Yes
Security database references:
In the Debian bugtracking system: [Bug 723043](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=723043).  
In Mitre's CVE dictionary: [CVE-2013-1443](https://security-tracker.debian.org/tracker/CVE-2013-1443).  

More information:

It was discovered that python-django, a high-level Python web
develompent framework, is prone to a denial of service vulnerability
via large passwords.


A non-authenticated remote attacker could mount a denial of service by
submitting arbitrarily large passwords, tying up server resources in
the expensive computation of the corresponding hashes to verify the
password.


For the oldstable distribution (squeeze), this problem has been fixed in
version 1.2.3-3+squeeze8.


For the stable distribution (wheezy), this problem has been fixed in
version 1.4.5-1+deb7u4.


For the unstable distribution (sid), this problem has been fixed in
version 1.5.4-1.


We recommend that you upgrade your python-django packages.





